### PR TITLE
Update README.md of dayjs

### PR DESCRIPTION
**Pull request by xxyuk**
### parse with locale 
According to https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#customparseformat

dayjs does support parse date with locale 

### week

According to https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#weekofyear,

dayjs does support set week of year

### CODE REVIEW

**Comment by stevemao** [comment]
> According to https://bundlephobia.com/result?p=dayjs@1.8.7, dayjs is tree-shakeable

Interesting. Did you try building with webpack and unused methods are removed?

**Comment by xxyuk** [comment]
@stevemao It dose support this. Check here: https://unpkg.com/dayjs@1.8.7/, you could find an `esm` folder with the bundled es module. That's the secret of tree-shaking.

**Comment by stevemao** [comment]
It exports `dayjs` as the default module. I don't see unused methods on it removed

**Comment by xxyuk** [comment]
@stevemao Oh I see.

**Pull request merged**
