### PR TITLE
Update "Time from now" date-fns example

### PR DESCRIPTION
**Pull request by vonkanehoffen**
The old one is no longer correct.

### CODE REVIEW

**Comment by cht8687** [comment]
@vonkanehoffen 
The fix you committed is v1.x API.
Actually, from 2.0, the API changed to `formatDistance` which is correct.

**Comment by cht8687** [comment]
@vonkanehoffen Based on the discussion above, I am going to close this PR. Thanks for your contribution though.

**Comment by vonkanehoffen** [comment]
Hadn't looked at the 2.0 API. [Just checked](https://www.npmjs.com/package/date-fns) and still in alpha - the current stable version is `1.29.0`. Still, your decision. :-)

**Comment by ODudek** [comment]
Yes the current stable version is 1.29.0 but we’re using 2.0 API in this project. Check package.json file to see which version.

**Pull request closed without merging**
