### PR TITLE
update library version

### LINKED ISSUE #78: Date-fns v2 is officially released
should upgrade to the official released version from alpha.23 to test out whether there are any breaking changes.

and benchmarking.

ref: https://github.com/date-fns/date-fns/releases/tag/v2.0.0?fbclid=IwAR3rrkytHDkVBxKk6FJOocMHp3qtLn4HZyYnqrD28JfC3QSfYUnXI4_67k4

### PR DESCRIPTION
**Pull request by cylim**
close #78 

Generally, most benchmark is getting worse due to my laptop is not as powerful as the one used to perform the test previously

### CODE REVIEW

**Comment by stevemao** [comment]
Could you also remove 

> Note that the provided examples of date-fns are for v2 which is in pre-release right now. See v1 docs for the current release.

**Comment by cht8687** [comment]
Good work!

**Comment by stevemao** [comment]
@cylim Why is screenshot.png deleted?

**Comment by cylim** [comment]
> @cylim Why is screenshot.png deleted?

@stevemao replaced, not deleted. The reason is upgrading libraries will affect the sizes. I can change it back if wanted to keep the original.

**Comment by stevemao** [comment]
Sorry, I thought it was deleted. Thanks for the PR

**Pull request closed without merging**
